### ISSUE TITLE
Error with npm run

### ISSUE THREAD

**Issue by jerearaujo03** [rappasoft/laravel-5-boilerplate#1241]
When I do ``npm run dev`` on a fresh installation I'm getting 

```
> @rappasoft/laravel-5-boilerplate@ dev /Users/jeremias/Documents/Projects/ANClub/Backend
> cross-var $npm_execpath run development


> @rappasoft/laravel-5-boilerplate@ development /Users/jeremias/Documents/Projects/ANClub/Backend
> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/cli.js:74
				throw err;
				^

SyntaxError: Invalid regular expression: /(?<!node_modules.*)[\\/]node_modules[\\/](jquery|bootstrap|popper.js|axios|sweetalert2|lodash)[\\/]/: Invalid group
    at new RegExp (<anonymous>)
    at Extract.createCacheGroup (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/components/Extract.js:104:25)
    at Extract.createSplitChunks (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/components/Extract.js:86:61)
    at Extract.config (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/components/Extract.js:76:35)
    at Extract.webpackConfig (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/components/Extract.js:60:59)
    at Mix.listen.config (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/components/ComponentFactory.js:75:54)
    at events.(anonymous function).forEach.handler (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/Dispatcher.js:34:47)
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/Mix.js:119:25)
    at WebpackConfig.build (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/src/builder/WebpackConfig.js:28:13)
    at Object.<anonymous> (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/laravel-mix/setup/webpack.config.js:29:38)
    at Module._compile (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/utils/convert-argv.js:115:13)
    at requireConfig (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/utils/convert-argv.js:117:6)
    at /Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/utils/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/utils/convert-argv.js:122:15)
    at yargs.parse (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/yargs/yargs.js:567:18)
    at /Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack-cli/bin/cli.js:375:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jeremias/Documents/Projects/ANClub/Backend/node_modules/webpack/bin/webpack.js:156:2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-5-boilerplate@ development: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @rappasoft/laravel-5-boilerplate@ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeremias/.npm/_logs/2019-05-08T16_35_02_370Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-5-boilerplate@ dev: `cross-var $npm_execpath run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @rappasoft/laravel-5-boilerplate@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeremias/.npm/_logs/2019-05-08T16_35_02_661Z-debug.log

```

How can I solve?

**Comment by jerearaujo03** [comment]
I haven't changed any file, it's all as it comes.

**Comment by rivajunior** [comment]
Which is your node version?

**Comment by jerearaujo03** [comment]
Ok I've updated my node and it solved the error.

**Comment by jerearaujo03** [comment]
Ok I've updated my node and it solved the error.
