### ISSUE TITLE
gulp SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by LunarDevelopment** [rappasoft/laravel-5-boilerplate#525]
I'm getting the below with `gulp watch`, have I missed a basic setup step with Elixir (which I'm unfamiliar with) perhaps? 

```
/Applications/MAMP/htdocs/Tweads/production/gulpfile.js:17
elixir((mix) => {
              ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)

```

**Comment by minedun6** [comment]
update node/npm or don't use it on homestead cuz he doesn't know where to gulp the files since on homestead it's virtual files.

**Comment by LunarDevelopment** [comment]
Cherrs,  I'll try updating node/ npm. 

I'm not using homestead.

**Comment by rappasoft** [comment]
Homestead is definitely a home run for developing Laravel apps!
