### ISSUE TITLE
Cannot run gulp or gulp watch commands

### ISSUE THREAD

**Issue by marcelgruber** [rappasoft/laravel-5-boilerplate#63]
Hello! I've been setting up the project and ran into this issue at the last step. Just wondering what your thoughts are.

Here is the error stack:

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/Projects/Laravel/node_modules/laravel-elixir/node_modules/babelify/index.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by marcelgruber** [comment]
Once I ran  sudo npm update, it works now.
